name: Build rust

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - rust/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rust

permissions:
  actions: read
  packages: write

jobs:
  push:
    name: ${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "1"
          - "1.20"
          - "1.30"
          - "1.40"
          - "1.50"
          - "1.60"
          - "1.70"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.IMAGE_NAME }}
          file: ./${{ env.IMAGE_NAME }}/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/dpkgsoft/pterodactyl-docker-images/${{ env.IMAGE_NAME }}:${{ matrix.tag }}